name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
        compiler: [gcc, clang]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev libusb-1.0-0-dev libboost-all-dev qt5-default qttools5-dev qtdeclarative5-dev libqt5svg5-dev libqt5opengl5-dev cmake

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install libusb qt
        brew upgrade qt
        brew link libusb
        brew link qt
        echo "/usr/local/opt/qt/bin" >> $GITHUB_PATH

    - name: Clone and build libsmu
      run: |
        git clone https://github.com/analogdevicesinc/libsmu.git
        cd libsmu
        mkdir build && cd build
        cmake -DBUILD_PYTHON=OFF -DCMAKE_INSTALL_PREFIX=/usr/local/ ..
        make
        sudo make install
        cd ../..

    - name: Build Pixelpulse2
      run: |
        mkdir build && cd build
        cmake ..
        make
        cd ..

    - name: Run macOS specific steps
      if: runner.os == 'macOS'
      run: |
        cd build
        /usr/local/opt/qt/bin/macdeployqt pixelpulse2.app -always-overwrite -verbose=2 -qmldir=../qml
        cd ..
        libsmupath="$(otool -L ./build/pixelpulse2.app/Contents/MacOS/pixelpulse2 | grep libsmu | cut -d " " -f 1)"
        libsmuid="$(echo ${libsmupath} | rev | cut -d "/" -f 1 | rev)"
        cp libsmu/build/src/${libsmuid} build/pixelpulse2.app/Contents/Frameworks/
        sudo install_name_tool -id @executable_path/../Frameworks/${libsmuid} build/pixelpulse2.app/Contents/Frameworks/${libsmuid}
        sudo install_name_tool -change ${libsmupath} @executable_path/../Frameworks/${libsmuid} build/pixelpulse2.app/Contents/MacOS/Pixelpulse2
        cd build
        /usr/local/opt/qt/bin/macdeployqt pixelpulse2.app -dmg -no-plugins
        for x in *.dmg ; do mv $x ${x%.dmg}${LDIST}.dmg ; done
        cd ..

    - name: Upload Release Asset
      if: runner.os == 'macOS' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/*.dmg
        name: pixelpulse2-${{ github.ref_name }}.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}